### PR TITLE
it changes as per users system mode

### PR DESCRIPTION
**Pull request by Pavan-Nambi**
image

### CODE REVIEW

**Comment by pavan-nambi** [comment]
had to comment main in css idk why u used main again with same color..etc in css

**Comment by pavan-nambi** [comment]
image

**Comment by pavan-nambi** [comment]
image

**Comment by pavan-nambi** [comment]
ok is there any preferred colour?

**Comment by IndigoWizard** [comment]
@pavan-nambi you can get inspiration from the palette contrast of [GitHub - The ReadME Project](https://github.com/readme/featured/global-forest-watch) blog posts color palette, it helps as an inspiration.

**Comment by pavan-nambi** [comment]
ok thanks

**Comment by pavan-nambi** [comment]
image

**Comment by pavan-nambi** [comment]
is that looking good or any changed you wish for?

**Comment by pavan-nambi** [comment]
nice

**Pull request merged**
